// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using PruebaDataaces.Datos.Configurations;
using PruebaDataaces.PruebaDataaces.Persistence.Configuration;
using PruebaDataaces.PruebaDataaces.Persistence.Configuration.dboSchema;
using System;
using System.Collections.Generic;
#nullable disable

namespace PruebaDataaces.Datos;

public partial class PruebaContext : DbContext
{
    public PruebaContext(DbContextOptions<PruebaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Persona> Personas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.PersonaConfiguration());

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
