// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using PruebaDataaces.PruebaDataaces.Persistence.Configuration;

namespace PruebaDataaces.Datos
{
    public partial class PruebaContext
    {

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
