// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using PruebaDataaces.PruebaDataaces.Persistence.Configuration;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PruebaDataaces.Datos
{
    public partial class PruebaContext
    {
        private IPruebaContextProcedures _procedures;

        public virtual IPruebaContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new PruebaContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IPruebaContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class PruebaContextProcedures : IPruebaContextProcedures
    {
        private readonly PruebaContext _context;

        public PruebaContextProcedures(PruebaContext context)
        {
            _context = context;
        }
    }
}
