// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using PruebaDataaces.PruebaDataaces.Persistence.Configuration.dboSchema;


namespace PruebaDataaces.PruebaDataaces.Persistence.Configuration.dboSchema;

public partial class Persona
{
    public short Id { get; set; }

    public string Username { get; set; }

    public string Cedula { get; set; }

    public string FirstName { get; set; }

    public string MidleName { get; set; }

    public string LastName { get; set; }

    public string LastNameSecond { get; set; }

    public string RazonSocial { get; set; }

    public bool Activo { get; set; }
}